# Atividade 13

## Tiago Vargas Pereira de Oliveira

#### 2021045050365

In [1]:
import numpy as np
import math

from numpy.linalg import pinv


In [2]:
sigmoid = np.vectorize(lambda x: 1 / (1 + math.exp(-x)))


Fiz com base nos exercícios, que pedem pra descobrir os pesos da camada oculta pra de saída.

Os pesos da camada de entrada pra oculta são aleatórios.

# Q1

**Implemente a RNA ELM com as seguintes saídas e entradas.**

**Entradas: `[1 1 1; 0 1 1; 1 0 1; 1 1 0; 0 0 1; 0 1 0; 1 0 0; 0 0 0 ]`.**

**Saída: `[1; 0; 0; 0; 0; 0; 0; 0]`.**

In [3]:
X = np.array([[1, 1, 1], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 0]])
T = np.array([1, 0, 0, 0, 0, 0, 0, 0])

w = np.random.random([3, 2])  # 2 neurônios na camada oculta


In [4]:
print(w)


[[0.14276326 0.74790132]
 [0.26735451 0.54540677]
 [0.22385512 0.01253524]]


In [5]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [6]:
print(betha)


[-1.04760046  1.14346984]


# Q2

**Implemente a RNA ELM para a porta AND com duas entradas e uma saída.**

In [7]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [0], [0], [1]])

w = np.random.random([2, 2])  # 2 neurônios na camada oculta


In [8]:
print(w)


[[0.39720547 0.62654498]
 [0.61309944 0.3138893 ]]


In [9]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [10]:
print(betha)


[[ 0.80626899]
 [-0.34334347]]


# Q3

**Implemente a RNA ELM para a porta OR com duas entradas e uma saída.**

In [11]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [1], [1], [1]])

w = np.random.random([2, 2])  # 2 neurônios na camada oculta


In [12]:
print(w)


[[0.38057169 0.80483395]
 [0.8645372  0.13062557]]


In [13]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [14]:
print(betha)


[[ 1.23646495]
 [-0.01814189]]


# Q3

**Implemente a RNA ELM para a porta OR com três entradas e uma saída.**

In [15]:
X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
T = np.array([[0], [1], [1], [1], [1], [1], [1], [1]])

w = np.random.random([3, 2])  # 2 neurônios na camada oculta


In [16]:
print(w)


[[0.51760158 0.16741813]
 [0.92310227 0.18011703]
 [0.2562084  0.96188445]]


In [17]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [18]:
print(betha)


[[0.95234786]
 [0.35890888]]
