# Atividade 13

## Tiago Vargas Pereira de Oliveira

#### 2021045050365

In [1]:
import numpy as np
import math

from numpy.linalg import pinv


In [2]:
sigmoid = np.vectorize(lambda x: 1 / (1 + math.exp(-x)))


# Q1

**Implemente a RNA ELM com as seguintes saídas e entradas.**

**Entradas: `[1 1 1; 0 1 1; 1 0 1; 1 1 0; 0 0 1; 0 1 0; 1 0 0; 0 0 0 ]`.**

**Saída: `[1; 0; 0; 0; 0; 0; 0; 0]`.**

In [3]:
X = np.array([[1, 1, 1], [0, 1, 1], [1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 0]])
T = np.array([1, 0, 0, 0, 0, 0, 0, 0])

w = np.random.random([3, 2])  # 2 neurônios na camada oculta


In [4]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [5]:
print(betha)


[0.08896787 0.12604045]


# Q2

**Implemente a RNA ELM para a porta AND com duas entradas e uma saída.**

In [6]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [0], [0], [1]])

w = np.random.random([2, 2])  # 2 neurônios na camada oculta


In [7]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [8]:
print(betha)


[[ 4.31579648]
 [-4.07285839]]


# Q3

**Implemente a RNA ELM para a porta OR com duas entradas e uma saída.**

In [9]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [1], [1], [1]])

w = np.random.random([2, 2])  # 2 neurônios na camada oculta


In [10]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [11]:
print(betha)


[[-5.44250859]
 [ 6.39542313]]


# Q3

**Implemente a RNA ELM para a porta OR com três entradas e uma saída.**

In [12]:
X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
T = np.array([[0], [1], [1], [1], [1], [1], [1], [1]])

w = np.random.random([3, 2])  # 2 neurônios na camada oculta


In [13]:
H = sigmoid(X @ w)
betha = pinv(H) @ T


Os pesos da camada oculta pra de saída são:

In [14]:
print(betha)


[[0.39123606]
 [0.9960493 ]]
